### ISSUE TITLE
2번째 피드백 및 과제

### ISSUE THREAD

**Issue by whatisand** [SullivanEducation/2018-Minecraft#1]
----------------------------------------------------------------------------------------------------
ㅋㅋㅋ제가 모르고 피드백 및 과제를 아두이노 팀한테 똑같이 올렸습니다.
어차피 공통된 사항이라 남겨두었는데, 피드백 돌려쓰기 아니냐고 오해하지 말아주세요ㅠㅠ...

----------------------------------------------------------------------------------------------------

### 내용

1,2차시 개발하는것 잘 보았습니다. 역시 여러번 경험이 있으니까 잘 하시는 것 같아요

이번에도 교육 피드백보단, 몇가지 과제를 드리도록 하겠습니다.
이번에는 1번만 한다고 생각하고, 다음주 월요일까지 찾을 수 있는 만큼 찾아보시면 됩니다.

지난번에 교육 요소라고 말씀 드린 부분이 있습니다.
저도 교육이론 뭐 이런걸 한게 아니니까 용어에 대해 민감하지 않으셔도 좋아요.
제가 생각한 교육요소는 예를들어서,
- 개념을 설명 후 질문을 한다.
- 학습지를 쓰게 한다.
- 영상 위주로 수업을 한다.
- 기타등등 이런 느낌의 요소들.

이라고 생각했습니다만, 여러분이 나름대로 생각한 교육적 방법론들이 교육 요소가 될 수 있을 것 같습니다.

### 질문

1. 기존에 있던 조이스틱 만들기 교육, 또는 비슷한 컨샙의 교육은 어느것이 있는지 찾아보고, 똑같거나 가장 비슷한거 하나 고르기
- 지금 1,2차시 참고에 적어두신 것 처럼 유튜브도 좋고요,
- 한차시 또는 단발성 유료교육,
- 학원 커리큘럼도 좋습니다.

이후에 시간이 남는다면 아래도 답을 해보세요, 어차피 다음 피드백때는 아래 내용을 물어볼 것입니다.

2. 똑같거나 가장 비슷하다고 생각한 교육은 어떤게 문제일지?
3. 그것과 여러분이 만드는 교육과 비교했을때, 우리는 어떤부분이 더 좋고, 어떤부분이 더 안좋은지?

정도입니다.

일단 1번에 대한 것만 해보고 저한테 알려주세요.

감사합니다.

**Comment by a1p4ca** [comment]
너무 흔한 블록코딩 플랫폼(스크래치, 엔트리)은 넣지 않았습니다.

| 이름 | 설명 | 비고 |
|:----:|----|----|
| Hour of Code | 1시간 동안 코딩을 배우는 온라인 교육 플랫폼. 마인크래프트 등 아이들에게 익숙한 테마를 배경으로 코딩을 배울 수 있음. | 이미 만들어진 틀 내에서만 진행할 수 있음. 오프라인 교육도 간간히 진행하지만 대부분 수도권 중심이다. |
| Code Combat | 쯔꾸르 게임으로 자바스크립트와 파이썬을 배움. | 쯔꾸르 게임. 아기자기하고 귀엽지만 요즘 아이들에겐 호불호가 갈릴 것 같다. |
| Tynker | 퍼즐을 풀면서 진행하고, 자신만의 게임도 제작할 수 있음. 블록코딩과 스위프트를 배울 수 있음. | 부제는 Coding for Kids |
| CodinGame | 게임으로 코딩을 배우기만 하는게 아니라, 멀티플레이 코딩배틀(!)도 하고 좀 남다르다. 화려한 그래픽이 특징인 것 같은데 아직 안 해봐서 잘 모르겠다. | 코딩을 처음 배우는 사람을 주 타겟으로 잡지는 않은 것 같다. 코딩으로 실시간 배틀이라니 참신하다. |
| CODE.GAME | 3D로 아기자기한 그래픽을 보며 힐링할 수 있다. 주는 과제도 힐링이 될지는 잘 모르겠다. | 일종의 코딩 플랫폼을 제공하는 것 같다. 활용 가능성이 높아보인다. 다양한 플랫폼을 지원한다. |
| 김왼손의 코딩교실 | 게임을 통해 파이썬을 공부할 수 있는 영상을 제작하는 크리에이터 | 마인컴뱃과 마인크래프트, 그리고 CheckiO, Khim Academy 등으로 파이썬 강좌를 입맛대로 고를 수 있도록 다양하게 제작했다. 또한 최근에는 파이썬이 아닌 게임으로(...) vim을 공부하는 영상도 제작했다. |

목록 중 저희 커리큘럼과 가장 유사하다고 생각되는 것은 아무래도 '김왼손의 코딩교실' 이라고 생각합니다.

**Comment by kattpish** [comment]
게임을 통해 코딩을 배운다는 점이 위 항목들과 저희 수업의 공통점이지만, 김왼손의 코딩 교실을 제외한 나머지는 플랫폼이고 김왼손의 코딩 교실은 수업이라는 차이점이 있습니다.

**Comment by whatisand** [comment]
정말 수고하셨어요!!
이번 이슈는 닫도록 하겠습니다. 다음 과제는 다음 이슈를 참고해주세요~
