### ISSUE TITLE
3차 피드백(9월 17일까지)

### ISSUE THREAD

**Issue by whatisand** [SullivanEducation/2018-Minecraft#2]
앞으로의 일정을 말씀드리겠습니다.

### 커리큘럼 계획서

10월 31일까지 10차시까지의 강의차시계획서가 완성되어야 합니다.

시험기간과 이것저것 제외하면 5~6주가 남은 것 같으니, 앞으로 한주에 2개의 강의차시계획서를 제출하시면 되겠습니다.

9월 17일(다음주 월요일)까지 3,4차시 강의차시계획서를 작성하여 제출해주세요.

### 과제

지난번에 자료조사를 부탁드렸는데, 진짜 잘해주셔서 고마워요!!!

지난번에 말씀드렸듯이, 다음 질문을 드리도록 하겠습니다.

지금 드리는 질문들이 어떤 것을 위해 필요한지 궁금하실 것 같아 첨언하자면,
지금까지 있던 교육과 여러분의 커리큘럼을 비교하여, “더 나은 교육”을 만들어 가는 과정입니다.

여러분이 찾은 ‘김왼손의 코딩교실’(아무래도 유튜브를 보신거겠죠?) 과 여러분의 커리큘럼을 비교하자면,
1. ‘김왼손의 코딩교실’은 어려분의 교육 목적을 달성하기에 어떤 부분이 문제일까요?
	1. 만약 문제가 될 부분이 잘 보이지 않는다면, ‘직접 자료 만들지 말고 유튜브에 있는 저 교육을 우리 수업에 사용하라고 하면?’라고 생각해보시면 좋을 것입니다. 저작권 이런거는 예외로 하고요.
	2. 제가 생각할때 예시) 김왼손은 게임을 이용하지 않기 때문에 코딩에 대한 장벽 허물기라는 목표를 달성 할 수 없다.

역시 시간이 되신다면, 다음 질문도 함께 답변해보세요.

2. ‘김왼손의 코딩교실’과 우리 커리큘럼을 비교했을때 장점과 단점 비교.

지금처럼만 해주시면 정말 좋은 커리큘럼이 나올 듯 합니다!! 감사합니다!!

**Comment by a1p4ca** [comment]
## Q1. '김왼손의 코딩교실’은 어려분의 교육 목적을 달성하기에 어떤 부분이 문제일까요?

1. 김왼손은 영상 시청자의 타겟을 고등학생 혹은 성인으로 설정하여 컨텐츠를 제작하는 것으로 보입니다. 따라서 저희 커리큘럼의 타겟인 중학생들에게는 내용의 이해가 어려울 수 있습니다.
2. 예시를 들어주신대로 김왼손은 프로그래밍 언어(파이썬)을 가르치는데 게임을 사용하지 않습니다. 따라서 단조로운 주입식 교육을 진행할 수 밖에 없고, 코딩을 왜 해야 하는지에 대한 근본적인 의문점을 해소해주지 않습니다.

## Q2. ‘김왼손의 코딩교실’과 우리 커리큘럼을 비교했을 때 장점과 단점 비교.

우리 커리큘럼을 기준으로 작성했습니다.

### 장점

1. 오프라인 교육의 장점 - 즉각적인 피드백, 질답 등 소통
2. `No Student Left Behind` - 학생 개개인의 역량에 맞추는 유연한 커리큘럼 진행

### 단점

1. 준비를 제대로 안 해온다면 말아먹을 수 있음 - 잘 해가야죠
2. 마인크래프트라는 플랫폼에 제한된 교육 - 자바스크립트의 활용 방향을 제시함으로써 극복 가능

2번째 질문에 대한 답은 잘 떠오르지가 않았어요 ㅠㅠ

**Comment by whatisand** [comment]
네 정말 좋습니다!!

여러분이 논의 하면서 감을 잡았을지 모르겠습니다.
결국 여러분이 생각한 **기존에 있던 코딩 문제점**이 무엇이고, 그것을 해결하기 위해서 여러분이 생각해 낸 해결책을 고민하면 좋습니다.

* 여려분이 장점이라고 생각한 요소들을 어떻게 하면 더 잘 이루어 낼수 있는지
* 여러분이 찾아낸 단점을 어떻게 해결할 수 있는지

아마 교육 전날까지 고민하셔야 할 것입니다.
저도 여러분과 마찬가지로 고민하는 입장입니다ㅎㅎ. 차시별 계획서는 계속해서 써주세요.
저도 생각나는게 있으면 공유할테니 여러분도 **꼭 팀원들과 여러분이 느낀 교육의 문제점과 해결책에 대해서 고민하고, 고민의 흔적을 글로 남겨두어 주세요.**

감사합니다.

### 다음 과제

시험기간을 고려하여 기간을 잡았는데요. 3주정도 남은것으로 보입니다.

1. 연휴가 끝나는 날인 9월 26일(수)까지 2개 차시를 작성하여 올려주세요.
쉬는 날에 많이 해두면 좋잖아요ㅎㅎ


### 그냥 드리는 말씀 

2. 꼭!! 교육에 대한 고민을 팀원들과 나누세요.
3. 설리번 활동을 기록으로 많이 남겨두면 나중에 도움이 많이 됩니다.

다음 과제는 다시 이슈로 올려드릴게요!
