### ISSUE TITLE
1차시에서 설치하는 부분에 대한 이슈

### ISSUE THREAD

**Issue by whatisand** [SullivanEducation/2018-Minecraft#4]
###### 참고로 제가 커리큘럼 계획서 보다가 보이는 피드백들은 개별 이슈로 만들어 드릴겁니다.
이렇게 개별로 말씀드리는 경우는 교육적 피드백보다는 말 그대로 피드백입니다.

----
1차시에 마인크래프트 세팅을 하는것으로 보았는데요.
보통 개발세팅에 하루에서 크게는 일주일까지 날려먹는 경우가 많았습니다.

제가 알기로는 지금 윈도우 10에는 마인크래프트 에듀케이션이 기본으로 깔려있는것으로 보이는데, 혹시 그렇지 않는 경우에 대해서 준비해둔 대비가 있는지요? 개발 세팅도 학습의 일부이긴 하지만, 마인크래프트 설치에 너무 오랜 기간이 걸리지 않는게 좋아 보입니다.

**Comment by kattpish** [comment]
마인크래프트 에듀케이션은 윈도우 10에 기본으로 깔려 있지는 않습니다만 스토어에서 무료로 깔 수 있습니다. 그리고 코드커넥션과 클래스룸 모드는 설치한 후 주소로 접속만 하면 되서 세팅에 큰 시간이 들 것 같진 않은데, 혹시 모르니깐 수업 전에 미리 한번 더 해보고 오래 걸릴 것 같다 싶으면 설치는 수업 전에 미리 해오는 방향으로 진행하겠습니다!

**Comment by whatisand** [comment]
마인크래프트 뿐만 아니라 개발 세팅 전반에 걸리는 시간을 체크하는게 좋아 보입니다. 혼자 집에서 할때는 금방 걸리는게 교육장소의 열악한 인터넷 환경에서는 오래 걸리는 경우가 있어요

**Comment by a1p4ca** [comment]
사실 저와 다해는 작년에 SW 교육 페스티벌에서 MS의 부스 운영을 도우면서 노트북 약 30대에 마크를 설치해본 경험이 있기 때문에 어느 정도 예상은 하고 있습니다. 물론 사전에 교육 환경에 대한 조사를 미리 해가서 교육을 계획대로 진행할 수 있도록 준비를 철저하게 하겠습니다 😃👌
