### ISSUE TITLE
다음 과제들 + 학생이 잘 이해했는지 평가하기

### ISSUE THREAD

**Issue by whatisand** [SullivanEducation/2018-Minecraft#5]
이제 강의 계획서는 마지막 차시까지 적당히 마무리 해주세요.

학생이 만들고 싶은 것을 만들고 있는지, 배운 것을 이해해서 만들었는지 확인하는 방법을 고민해보세요.

마인크래프트로 미니게임 만들기의 경우 학생이 그간 배운 내용을 바탕으로 게임 기획서(소개서? 정도로 간단히)을 써본다든지, 그 기획서 안에 배운 개념을 적게 한다든지 하는 것이죠.

저는 설리번에서

학생이 만들고 싶은 것을 찾았는지, 기존에 만들고 싶던 것을 만들 방법을 찾았는지가 중요한 척도라고 생각해요.

관련해서 한번 고민해보세요!

**Comment by kattpish** [comment]
미니게임을 만드는 차시에서, 기획서는 이미 계획되어 있던 부분입니다만, 기획서안에 배운 개념을 적게 하는 건 굉장히 좋은 아이디어인 것 같습니다. 저희 커리큘럼에 적용해보도록 하겠습니다 ㅎㅎ
